---
- name: GIS
  hosts: gis
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - ../ansible_common/common
    - { role: postgis, db_name: gis, db_passwd: password }
    - mapserver
    - ../ansible_common/maven
    - ../ansible_common/tomcat
    - { role: ../ansible_common/firewalld, PORTS:["80/tcp","443/tcp","5432/tcp","4848/tcp","8080/tcp"]}
