---
- name: install git command
  yum: name=git  state=present

- name: download postgis-java source
  git:
    repo=https://github.com/postgis/postgis-java.git
    dest="{{ src_dir }}/postgis-java"
    force=yes

- name: build postgis jdbc driver
  command:
    chdir="{{ src_dir }}/postgis-java"
    /usr/local/bin/mvn package

- name: Create jdbc directory
  file: path=/usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/jdbc state=directory

- name: install postgresql jdbc driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar
    dest: "/usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/jdbc"
    validate_certs: false

- name: install postgis jdbc driver
  command:
    find "{{ src_dir }}/postgis-java" -name postgis-*.jar -exec cp -fv {} "/usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/jdbc" \;
