---
# This playbook is based on "An almost idiot's guide to install PostgreSQL 9.5, PostGIS 2.2 and pgRouting 2.1.0 with Yum"
# http://www.postgresonline.com/journal/archives/362-An-almost-idiots-guide-to-install-PostgreSQL-9.5,-PostGIS-2.2-and-pgRouting-2.1.0-with-Yum.html

# see https://yum.postgresql.org/repopackages.php
# I know the yum task can download RPM. But the yum task can't download through http-proxy.
- name: Install PostgreSQL yum site
  get_url:
    url: https://download.postgresql.org/pub/repos/yum/{{ PG_VER }}.{{ PG_REV }}/redhat/rhel-7-x86_64/pgdg-centos{{ PG_VER }}{{ PG_REV }}-{{ PG_VER }}.{{ PG_REV }}-3.noarch.rpm
    dest: /tmp
    validate_certs: false
  when: (init is not defined) or (init)

- yum: name=/tmp/pgdg-centos{{ PG_VER }}{{ PG_REV }}-{{ PG_VER }}.{{ PG_REV }}-3.noarch.rpm state=present
  when: (init is not defined) or (init)

- name: Install PostgreSQL
  yum: name={{ item }}  state=present
  with_items:
    - postgresql{{ PG_VER }}{{ PG_REV }}
    - postgresql{{ PG_VER }}{{ PG_REV }}-server
    - postgresql{{ PG_VER }}{{ PG_REV }}-libs
    - postgresql{{ PG_VER }}{{ PG_REV }}-contrib
    - postgresql{{ PG_VER }}{{ PG_REV }}-devel
    - postgis2_{{ PG_VER }}{{ PG_REV }}
    - postgis2_{{ PG_VER }}{{ PG_REV }}-client
    - ogr_fdw{{ PG_VER }}{{ PG_REV }}
    - pgrouting_{{ PG_VER }}{{ PG_REV }}
    - python-psycopg2
  when: (init is not defined) or (init)

- name: PostgreSQL initdb
  command:
    /usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/bin/postgresql{{ PG_VER }}{{ PG_REV }}-setup initdb
  register:
    initdb_result
  failed_when: initdb_result.rc not in [0, 1]
  changed_when: initdb_result.rc == 0
  when: (init is not defined) or (init)

- lineinfile:
    dest=/var/lib/pgsql/{{ PG_VER }}.{{ PG_REV }}/data/postgresql.conf
    insertbefore="#listen_addresses = 'localhost'"
    line="listen_addresses = '*'"
  when: (init is not defined) or (init)

- name: append access settings
  lineinfile:
    dest=/var/lib/pgsql/{{ PG_VER }}.{{ PG_REV }}/data/pg_hba.conf
    insertafter="#[ ]+TYPE[ ]+DATABASE[ ]+USER[ ]+ADDRESS[ ]+METHOD"
    line={{ item }}
  with_items:
    - 'host    {{ db_name }}         {{ db_name }}         0.0.0.0/0               md5'
    - 'host    {{ db_name }}         {{ db_name }}         127.0.0.1/32            md5'
    - 'host    {{ db_name }}         {{ db_name }}         ::1/128                 md5'

- name: PostgreSQL service setup
  service:
    name="postgresql-{{ PG_VER }}.{{ PG_REV }}"
    state=restarted
    enabled=yes

- name: Installing adminpack
  become: yes
  become_user: postgres
  command:
    /usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/bin/psql -p 5432 -c "CREATE EXTENSION adminpack;"
  ignore_errors: yes

- name: Create db
  become: yes
  become_user: postgres
  postgresql_db:
    name={{ db_name }}
    encoding='UTF-8'
    lc_collate='en_US.UTF8'
    lc_ctype='en_US.UTF8'
    template='template0'

- name: create user
  become: yes
  become_user: postgres
  postgresql_user:
    db={{ db_name }}
    name={{ db_name }}
    password={{ db_passwd }}
    priv=ALL
    state=present
    login_user=postgres

- name: Installing gis extension to {{ db_name }}
  become: yes
  become_user: postgres
  command:
    /usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/bin/psql -p 5432 -d {{ db_name }} -c "{{ item }}"
  with_items:
    - "CREATE EXTENSION postgis;"
    - "CREATE EXTENSION postgis_topology;"
    - "CREATE EXTENSION ogr_fdw;"
    - "CREATE EXTENSION pgrouting;"
    - "grant usage on schema topology to {{ db_name }};"
    - "grant all on all tables in schema topology to {{ db_name }};"
    - "grant usage, select on all sequences in schema topology to {{ db_name }};"
  ignore_errors: yes

- name: Check Postgis Status
  become: yes
  become_user: postgres
  command:
    /usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/bin/psql -p 5432 -d {{ db_name }} -c "SELECT postgis_full_version();"
  register: postgis_result

- debug: var=postgis_result.stdout_lines

- name: Check Pgroute Status
  become: yes
  become_user: postgres
  command:
    /usr/pgsql-{{ PG_VER }}.{{ PG_REV }}/bin/psql -p 5432 -d {{ db_name }} -c "SELECT * FROM pgr_version();"
  register: pgroot_result

- debug: var=pgroot_result.stdout_lines
