---
# CentOS6 provides mapserver in yum repository. But CentOS7 put an end to publish.
# So, we must compile mapserver.
# http://mapserver.org/installation/unix.html

- name: Install apache
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - memcached
    - proj-epsg
    - ipa-gothic-fonts.noarch # Japanese Gothic-typeface OpenType font by IPA
    - ipa-mincho-fonts.noarch # Japanese Mincho-typeface OpenType font by IPA
    - ipa-pgothic-fonts.noarch # Japanese Proportional Gothic-typeface OpenType font by IPA
    - ipa-pmincho-fonts.noarch # Japanese Proportional Mincho-typeface OpenType font by IPA

- name: Install build tools
  yum: name={{ item }} state=present
  with_items:
    - make
    - cmake
    - gcc
    - gcc-c++
    - swig

- name: Install GIS tool
  yum: name={{ item }} state=present
  with_items:
    - gdal
    - gdal-python

- name: Install required libraries for mapserver
  yum: name="{{ item }}-devel" state=present
  with_items:
    - python
    - java-1.8.0-openjdk
    - httpd
    # Required External Libraries
    - libpng
    - freetype
    - libjpeg
    - libgeotiff
    - zlib
    # Highly Recommended Libraries¶
    - proj
    # - proj-epsg
    - libcurl
    - gdal
    # Optional External Libraries
    - geos
    - libxml2
    - giflib
    - fcgi
    - cairo
    - libxslt
    - openssl
    - librsvg2
    - pixman
    # non ascii characters
    - fribidi
    - harfbuzz
    # for mapcache
    - libmemcached
    - libtiff
    - libgeotiff
    - db4
    - pcre
    - sqlite

- name: Check whether mapserver was installed or not
  stat: path=/usr/local/bin/mapserver
  register: mapserver

- stat: path={{ src_dir }}/{{ mapserver_version }}.tar.gz
  register: tarball
  when: not mapserver.stat.exists

##########
# mapserver

# default timeout is 10sec, but its too tight for osgeo.org
- name: Download mapserver source
  get_url:
    url: http://download.osgeo.org/mapserver/{{ mapserver_version }}.tar.gz
    dest: "{{ src_dir }}"
    timeout: 60
  when: (not mapserver.stat.exists) and (not tarball.stat.exists)

- name: Expand mapserver source
  command:
    chdir={{ src_dir }}
    tar xf {{ mapserver_version }}.tar.gz
  when: not mapserver.stat.exists

- name: Create work directory for building mapserver
  file: path={{ src_dir }}/{{ mapserver_version }}/build state=absent force=yes
  ignore_errors: yes

- name: Create work directory for building mapserver
  file: path={{ src_dir }}/{{ mapserver_version }}/build state=directory

- name: Configure mapserver
  command:
    chdir={{ src_dir }}/{{ mapserver_version }}/build
    cmake -DCMAKE_PREFIX_PATH=/usr/pgsql-9.6 \
    -DWITH_CURL=ON \
    -DWITH_RSVG=ON \
    -DWITH_PIXMAN=ON \
    -DWITH_CLIENT_WFS=ON \
    -DWITH_CLIENT_WMS=ON \
    -DWITH_SOS=ON \
    -DWITH_KML=ON \
    -DWITH_XMLMAPFILE=ON \
    -DWITH_POSTGIS=ON \
    -DWITH_PYTHON=ON \
    -DWITH_JAVA=ON
    ../
  when: not mapserver.stat.exists

- name: Make mapserver
  command:
    chdir={{ src_dir }}/{{ mapserver_version }}/build
    make
  when: not mapserver.stat.exists

- name: Install mapserver
  command:
    chdir={{ src_dir }}/{{ mapserver_version }}/build
    make install
  when: not mapserver.stat.exists

- name: Create symbolic link
  file: src=/usr/local/bin/mapserv dest=/var/www/cgi-bin/mapserv state=link mode="o+x"

- name: Create the directory that contains mapfile
  file: path=/opt/maps state=directory owner=apache group=apache

##########
# mapcache
- name: Download mapcache source
  git:
    repo=https://github.com/mapserver/mapcache.git
    dest="{{ src_dir }}/mapcache"

- name: Create work directory for building mapcache
  file: path={{ src_dir }}/mapcache/build state=directory

- name: Configure mapcache
  command:
    chdir={{ src_dir }}/mapcache/build
    cmake .. -DWITH_MEMCACHE=1 -DWITH_BERKELEY_DB=1

- name: Make mapcache
  command:
    chdir={{ src_dir }}/mapcache/build
    make

- name: Install mapcache
  command:
    chdir={{ src_dir }}/mapcache/build
    make install

- name: Create the directory that contains mapcache
  file: path=/opt/mapcache state=directory owner=apache group=apache

- copy:
    src: 01-mapcache.conf
    dest: /etc/httpd/conf.modules.d

- copy:
    src: mapcache.conf
    dest: /etc/httpd/conf.d

- copy:
    remote_src: True
    src: /usr/local/src/mapcache/mapcache.xml
    dest: /opt/mapcache/mapcache.xml

##########
# Apache Settings

# To Create the patch file:
# 1. login remote redmine server
# 2. backup httpd.conf to httpd.conf.org
# 3. change httpd.conf
# 4. exit redmine server to ansible host
# 5. run remote diff command from ansible host
#    $ vagrant ssh gis -- sudo diff /etc/httpd/conf/httpd.conf.org /etc/httpd/conf/httpd.conf > httpd.conf.patch
- name: apply patch to /etc/httpd/conf/httpd.conf
  patch: >
    src=httpd.conf.patch
    dest=/etc/httpd/conf/httpd.conf
    backup=yes
  ignore_errors: yes

- name: update shared lib settings (ldconfig)
  command:
    ldconfig

- name: Restart apache
  service:
    name=httpd
    state=restarted
    enabled=yes
